### ISSUE TITLE
Status of east.bib in relationship to bibtex entries on site

### ISSUE THREAD

**Issue by kellner** [ea-east/east-biblio#22]
This is more of a request for clarification than an issue. I have noticed for several cases now that the BibTeX data shown on the website is fine while the respective entries in east.bib have fields missing. I tested the east.bib file also against one particular validator (https://biblatex-linter.herokuapp.com/), and it came up with a significant number of errors, plus it contains entries that probably shouldn't be there (journal names). Could you please clarify what the status of the currently available east.bib is?

**Comment by pchiou6932** [comment]
I suspect the missing fields in east.bib have something to do with the linking function of Tamboti. In Tamboti, an entry (mostly entries for journal article and for article in an edited volume) can be created through another entry (ex: entry for journal or edited volume) to which it should be linked. This means, in the mods, we dont have the fields linked to another entry, like the journal title, but rather the xlink:href, which then leads to the corresponding fields in east.bib missing.
Now a question is, if my suspicion is correct, @paddymcall is there any way to automatically get the missing information in east.bib from the xlink:href in the mods?

As for the existence of journal names in east.bib, it also goes back to Tamboti, since we need the entry for journal to link the entry for article.

**Comment by paddymcall** [comment]
As to the status: east.bib is a biblatex document that will become the
authoritative source for the bibliographic records on EAST.

Currently, new records should be added through the admin interface, and
then added separately here in east.bib.

On Mon, Feb 08 2021, pchiou6932 wrote:

> Now a question is, if my suspicion is correct, @paddymcall is there
> any way to automatically get the missing information in east.bib from
> the xlink:href in the mods?
>
> As for the existence of journal names in east.bib, it also goes back
> to Tamboti, since we need the entry for journal to link the entry for
> article.

That’s right.  There is no fully automatic way to update the entries,
however.  We’ll need to go through them (see TODOs below), but there are
certain recurring problems which the biblatex records present on
east.ikga.oeaw.ac.at can help us with quite a bit.  The current biblatex
records on EAST are not ideal for a full biblatex database, however,
since they have no cross-references at all.  They are intended as
standalone records for download.

To make east.bib fully functional, we need to do two things (TODO):

- [ ] Fill in the missing pieces from what is on east.ikga.oeaw.ac.at, and
  make it validate (there are several validation tools).

- [ ] Enable a supervised exchange between east.ikga.oeaw.ac.at and
  east.bib: new (user contributed) records need to be edited and put
  into east.bib, and then east.bib needs to be loaded by the site to
  show the updated entries.

I am planning to finish this in the next two months.

**Comment by kellner** [comment]
Thank you, I consider this issue closed, then.
